# Generated by Django 2.2 on 2019-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_person_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='login',
            field=models.CharField(default='cock', max_length=20, unique=True),
        ),
    ]
