# Generated by Django 2.2 on 2019-05-02 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190502_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
